# Generated by Django 2.2.5 on 2019-11-04 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_schedule',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('class1', models.CharField(blank=True, max_length=200, null=True)),
                ('class2', models.CharField(blank=True, max_length=200, null=True)),
                ('class3', models.CharField(blank=True, max_length=200, null=True)),
                ('class4', models.CharField(blank=True, max_length=200, null=True)),
                ('class5', models.CharField(blank=True, max_length=200, null=True)),
                ('class6', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classes_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('major_id', models.IntegerField(default=25)),
                ('class_extension', models.CharField(max_length=200)),
                ('credit', models.IntegerField(default=25)),
            ],
        ),
    ]
