# Generated by Django 2.2.5 on 2019-11-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ez_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes_list',
            name='major_id',
        ),
        migrations.AddField(
            model_name='classes_list',
            name='major',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
